recall/urls.py
from django.conf.urls import url
from recall import views
from .views import CreateScheduleView, ViewScheduleView, PastRecallView, ScheduleDetailView, ScheduleUpdateView, ScheduleDeleteView, ContactView
from .views import PatientFormView, PatientListView, PatientDetailView, PatientUpdateView, PatientDeleteView


app_name = 'recall'
urlpatterns = [
	url(r'^contact/$', ContactView.as_view(), name='contact'),
	url(r'^patient_delete(?P<pk>\d+)$', PatientDeleteView.as_view(), name='patient_delete'),
	url(r'^patient_update(?P<pk>\d+)$', PatientUpdateView.as_view(), name='patient_update'),
	url(r'^patient_detail(?P<pk>\d+)$', PatientDetailView.as_view(), name='patient_detail'),
	url(r'^patient_list/$', PatientListView.as_view(), name='patient_list'),
	url(r'^add_patient/$', PatientFormView.as_view(), name='add_patient'),
	url(r'^detail_recall(?P<pk>\d+)$', ScheduleDetailView.as_view(), name='detail_recall'),
	url(r'^update_recall(?P<pk>\d+)$', ScheduleUpdateView.as_view(), name='update_recall'),
	url(r'^delete_recall(?P<pk>\d+)$', ScheduleDeleteView.as_view(), name='delete_recall'),
	url(r'^past_recall/$', PastRecallView.as_view(), name='past_recall'),
	url(r'^view_recall/$', ViewScheduleView.as_view(), name='view_recall'),
	url(r'^create_recall/$', CreateScheduleView.as_view(), name='create_recall'),
]

recallmanager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView

from recall import urls as recall_url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recall/', include(recall_url)),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

recall/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from datetime import date 
from django.core.exceptions import ValidationError


# Create your models here.

class Patient(models.Model):
	card_number = models.CharField("Card Number", unique=True, max_length=30, blank=False)
	patient_name = models.CharField("Patient Name", max_length=50, help_text="Title Surname Firstname", blank=False)
	sex = (
		('Male', 'Male'),
		('Female', 'Female'),
	)

	sex = models.CharField("Sex", max_length=7, choices=sex, blank=False)
	date_of_birth = models.DateField("Date of Birth", help_text="Please use the following format: <em>YYYY-MM-DD</em>", blank=True)
	phone_number = models.CharField("Phone Number", max_length=30, blank=False)
	email = models.EmailField("Email", max_length=50, blank=True)
	address = models.CharField("Address", max_length=100, blank=True)
	occupation = models.CharField("Occupation", max_length=50, blank=True)
	hmo = models.CharField("HMO", max_length=100, help_text="Name of HMO(HMO ID Number)", blank=True)


	class Meta:
		ordering = ['card_number']

	def __str__(self):
		return self.patient_name

	def get_absolute_url(self):
		return reverse('recall:patient_detail', kwargs={'pk': self.pk})



class Schedule(models.Model):
	patient = models.CharField("Patient Name", max_length=50, help_text="Title Surname Firstname", blank=False)
	date_of_visit = models.DateField("Date of Visit", help_text="Please use the following format: <em>YYYY-MM-DD</em>", blank=False)
	summary_of_visit = models.TextField("Summary of Visit", max_length=500, blank=True)
	date_of_recall = models.DateField("Date of Recall", help_text="Please use the following format: <em>YYYY-MM-DD</em>", blank=False)
	reason_for_recall = models.TextField("Reason for Recall", max_length=200, blank=True)

	RECALL_STATUS = (
		('On Schedule', 'On Schedule'),
		('A Reminder', 'A Reminder'),
	)

	recall_status = models.CharField("Recall Status", max_length=15, choices=RECALL_STATUS, blank=True, default='On Schedule')




	class Meta:
		ordering = ['date_of_recall']
		

	def __str__(self):
		return self.patient

	def get_absolute_url(self):
		return reverse('recall:detail_recall', kwargs={'pk': self.pk})

	def clean(self):
		date_of_recall = self.date_of_recall

		if date_of_recall < date.today():
			raise ValidationError('You cannot schedule a recall for the past. Please check your date')


	

	

recall/forms.py
from django import forms


class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    # the new bit we're adding
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].label = 'Your name'
        self.fields['contact_email'].label = 'Your email'
        self.fields['content'].label = 'Enter your message here'

recall/views.py
from django.conf import settings
from django.db.models import Q
from datetime import date 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy 
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import FormView
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template import Context
from django.template.loader import get_template
from django.shortcuts import render
from recall.models import Patient
from recall.models import Schedule
from recall.forms import ContactForm




class PatientFormView(CreateView):

	model = Patient
	template_name = 'recall/add_patient.html'
	fields = ['card_number', 'patient_name', 'sex', 'date_of_birth', 'phone_number', 'email', 'address', 'occupation', 'hmo']
	success_url = reverse_lazy('recall:add_patient')
	success_message = 'Patient successfully added'


class PatientListView(ListView):

	model = Patient
	template_name = 'recall/list_patient.html'
	context_object_name = 'patients'
	paginate_by = 1

	def get_queryset(self, *args, **kwargs):
		queryset_list = Patient.objects.all()
		query = self.request.GET.get("q")
		
		if query:
			queryset_list = queryset_list.filter(
				Q(card_number__icontains=query)|
				Q(patient_name__icontains=query)
				).distinct()
		return queryset_list


class PatientDetailView(DetailView):

	model = Patient
	template_name = 'recall/detail_patient.html'
	context_object_name = 'patients'


class PatientDeleteView(SuccessMessageMixin, DeleteView):

	model = Patient
	template_name = 'recall/delete_patient.html'
	success_url = reverse_lazy('recall:patient_list')


class PatientUpdateView(SuccessMessageMixin, UpdateView):


	model = Patient
	template_name = 'recall/patient_update.html'
	fields = ['card_number', 'patient_name', 'sex', 'date_of_birth', 'phone_number', 'email', 'address', 'occupation', 'hmo']
	success_url = reverse_lazy('recall:patient_list') 
	success_message = 'Patient successfully added'


class CreateScheduleView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    #Powers a form to create a new recall

	model = Schedule
	template_name = 'recall/create_recall.html'
	fields = ['patient', 'date_of_visit', 'summary_of_visit', 'date_of_recall', 'reason_for_recall', 'recall_status']
	success_url = reverse_lazy('recall:create_recall')
	success_message = 'Recall successfully created'


class ViewScheduleView(LoginRequiredMixin, ListView):

	#Shows users a list of appointments.  

	model = Schedule
	template_name = 'recall/view_recall.html'
	context_object_name = 'view_recall' 
	paginate_by = 2
	queryset_list = Schedule.objects.exclude(date_of_recall__lt=date.today())

	
	def get_queryset(self, *args, **kwargs):
		queryset_list = Schedule.objects.exclude(date_of_recall__lt=date.today())
		query = self.request.GET.get("q")
		
		if query:
			queryset_list = queryset_list.filter(
				Q(date_of_recall__icontains=query)|
				Q(patient__icontains=query)
				).distinct()
		return queryset_list


class PastRecallView(ListView):

	model = Schedule
	template_name = 'recall/past_recall.html'
	context_object_name = 'past_recall'
	paginate_by = 5
	queryset_list = Schedule.objects.filter(date_of_recall__lt=date.today())


	def get_queryset(self, *args, **kwargs):
		queryset_list = Schedule.objects.filter(date_of_recall__lt=date.today())
		query = self.request.GET.get("q")
		
		if query:
			queryset_list = queryset_list.filter(
				Q(date_of_recall__icontains=query)|
				Q(patient__icontains=query)
				).distinct()
		return queryset_list


	
class ScheduleDetailView(DetailView):

	#Shows users a single appointment

	model = Schedule
	template_name = 'recall/detail_recall.html'
	context_object_name = 'schedule'

class ScheduleUpdateView(SuccessMessageMixin, UpdateView):
	#powers a form to edit existing recall

	model = Schedule
	template_name = 'recall/schedule_form.html'
	fields = ['patient', 'date_of_visit', 'summary_of_visit', 'date_of_recall', 'reason_for_recall', 'recall_status']
	success_url = reverse_lazy('recall:view_recall')
	success_message = 'Recall successfully updated'



class ScheduleDeleteView(SuccessMessageMixin, DeleteView):
	#prompts user to confirm deletion of a recall

	model = Schedule
	success_url = reverse_lazy('recall:view_recall')


class ContactView(FormView):
    form_class = ContactForm
    success_url = reverse_lazy('recall:contact')
    template_name = 'contact.html'


    def form_valid(self, form):
    	contact_name = form.cleaned_data['contact_name']
    	contact_email = form.cleaned_data['contact_email']
    	form_content = form.cleaned_data['content']

    	template = get_template('contact_template.txt')
    	context = {
    		'contact_name': contact_name,
    		'contact_email': contact_email,
    		'form_content': form_content
    		}
    	content = template.render(context)

    	email = EmailMessage(
    		'New contact form submission',
    		content,
    		'Your website ' + '',
    		['onyeka.ezenwankwo@gmail.com'],
    		headers = {'Reply-To': contact_email}
    		)
    	email.send()
    	return super(ContactView, self).form_valid(form)
    success_message = 'Thanks for contacting us, we will get back to you shortly.'

recall/templates/recall/add_patient.html
{% extends 'dashboard.html' %}

{% load bootstrap %}

{% block content %}

<div style="background-color: #0D96FF !important" class="container-fluid">
	<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12">
			<h1><b>Add Patient</b></h1>
			</div>
		</div>
	</div>
	<br>
</div><br>

<div class="container">
<div class="row">
<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3" class="form-group">
	<form method="POST" action="{% url 'recall:add_patient' %}" class="form">
		{{ form|bootstrap }}
		{% csrf_token %}
		<input type="submit" value="Add Patient" class="btn btn-success"> 
	</form>
</div>
</div>
</div><br>

{% endblock %}

recall/templates/recall/create_recall.html
{% extends 'dashboard.html' %}

{% load bootstrap3 %}
{% load bootstrap %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}


{% block title %}Create Recall | {{ block.super }}{% endblock %}

{% block content %}
<div style="background-color: #0D96FF !important" class="container-fluid">
	<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12">
			<h1><b>Create Recall</b></h1>
			<h3>Today is {% now "D d M Y" %}: {% now "H:i" %}</h3>
			</div>
		</div>
	</div>
	<br>
</div>
			

<div class="container"><br>
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3" class="form-group">
			{% if messages %}
			{% bootstrap_javascript jquery=1 %}
			{% bootstrap_messages %}
			{% endif %}
			<form method="POST" action="{% url 'recall:create_recall' %}" class="form">
			{{ form|bootstrap }}
			{% csrf_token %}
			<input type="submit" value="Create" class="btn btn-success"> 
			</form>
		</div>
	</div>
</div>
{% endblock %}

recall/templates/recall/delete_patient.html
{% extends 'dashboard.html' %}

{% load bootstrap3 %}


{% block title %}Delete Recall | {{ block.super }}{% endblock %}

{% block content %}
<div style="background-color: #0D96FF !important" class="container-fluid">
	<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12">
			<h1><b>Delete Patient</b></h1>
			</div>
		</div>
	</div>
	<br>
</div>

<div class="container">
	<div class="row">
		<div class="col-sm-6 col-md-6">
			<form method="POST" action="">
			{% csrf_token %}
			<h3>Are you sure you want to delete the record for "{{ patient }}"?</h3>
			{% buttons %}
		    	<button type="submit" class="btn btn-danger">
		      		{% bootstrap_icon "remove" %} Delete
		    	</button>
		  	{% endbuttons %}
			</form>
		</div>
	</div>
</div>
{% endblock %}

recall/templates/recall/detail_patient.html
{% extends 'dashboard.html' %}


{% block title %}Patient Detail | {{ block.super }}{% endblock %}

{% block content %}
<div style="background-color: #0D96FF !important" class="container-fluid">
	<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12">
			<h1><b>Patient Detail</b></h1>
			</div>
		</div>
	</div>
	<br>
</div>

<br>

<div class="container">
<div class="row">
<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Card Number</h3>
  </div>
  <div class="panel-body">
    {{ patients.card_number }} 
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Name</h3>
  </div>
  <div class="panel-body">
    {{ patients.patient_name }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Sex</h3>
  </div>
  <div class="panel-body">
    {{ patients.sex }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Date of Birth</h3>
  </div>
  <div class="panel-body">
    {{ patients.date_of_birth }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Phone Number</h3>
  </div>
  <div class="panel-body">
    {{ patients.phone_number }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Email</h3>
  </div>
  <div class="panel-body">
    {{ patients.email }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Address</h3>
  </div>
  <div class="panel-body">
    {{ patients.address }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Occupation</h3>
  </div>
  <div class="panel-body">
    {{ patients.occupation }}
  </div>
 </div>
 <div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Health Management Organisation</h3>
  </div>
  <div class="panel-body">
    {{ patients.hmo }}
  </div>
 </div>
 </div>
</div>
</div>
  
{% endblock %}

recall/templates/recall/detail_recall.html
{% extends 'dashboard.html' %}


{% block title %}Detail Recall | {{ block.super }}{% endblock %}

{% block content %}
<div style="background-color: #0D96FF !important" class="container-fluid">
	<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12">
			<h1><b>Detail Recall</b></h1>
			</div>
		</div>
	</div>
	<br>
</div>

<br>

<div class="container">
<div class="row">
<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Patient ID</h3>
  </div>
  <div class="panel-body">
    {{ schedule.card_number }} 
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Name</h3>
  </div>
  <div class="panel-body">
    {{ schedule.patient }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Date of Visit</h3>
  </div>
  <div class="panel-body">
    {{ schedule.date_of_visit }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Summary of Visit</h3>
  </div>
  <div class="panel-body">
    {{ schedule.summary_of_visit }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Date of Recall</h3>
  </div>
  <div class="panel-body">
    {{ schedule.date_of_recall }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Reason for Recall</h3>
  </div>
  <div class="panel-body">
    {{ schedule.reason_for_recall }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Recall Status</h3>
  </div>
  <div class="panel-body">
    {{ schedule.recall_status }}
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Phone Number</h3>
  </div>
  <div class="panel-body">
    {{ schedule.phone_number }}
  </div>
 </div>
 </div>
</div>
</div>
  
{% endblock %}

recall/templates/recall/list_patient.html
{% extends 'dashboard.html' %}



{% block content %}

<div style="background:#0D96FF !important" class="container-fluid">
    <br>
    <div class="container">
        <div class="row">
           <h1><b>View Patients</b></h1>
           <form method="GET" action="">
             <input type="text" class="form-control input-md" name="q" placeholder="Enter Card Number or Name" value="{{ request.GET.q }}"/>
             <input type="submit" value="Search" class="btn btn-success">  
           </form>
       </div>
    </div>
    <br>
</div>

<br>

<div class="container">
<div  class="table-responsive" class="row">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr class="success">
        <th><span>Card Number</span></th>
        <th><span>Name</span></th>
        <th><span>Phone</span></th>
        <th class="text-center"><span>Actions</span></th>
      </tr>
    </thead>
    <tbody>
    {% for patient in patients %}  
      <tr>
        <td>{{ patient.card_number }}</td>
        <td><a href="{{ patient.get_absolute_url }}">{{ patient.patient_name }}</a></td>
        <td>{{ patient.phone_number }}</td>
        <td class="text-center">
            <a class="btn btn-info btn-xs" href="{% url 'recall:patient_update' patient.pk %}"><span class="glyphicon glyphicon-edit"></span>Edit</a>
            <a class="btn btn-danger btn-xs" href="{% url 'recall:patient_delete' patient.pk %}"><span class="glyphicon glyphicon-remove"></span>Del</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
{% endif %}
</div>

{% endblock %}

recall/templates/recall/past_recall.html
{% extends 'dashboard.html' %}


{% block title %}View Recalls | {{ block.super }}{% endblock %}

{% block content %}
<div style="background:#0D96FF !important" class="container-fluid">
    <br>
    <div class="container">
        <div class="row">
           <h1><b>View Past Recalls</b></h1>
           <form method="GET" action="">
             <input type="text" class="form-control input-md" name="q" placeholder="Enter Name or Date of Recall(YYYY-MM-DD)" value="{{ request.GET.q }}"/>
             <input type="submit" value="Search" class="btn btn-success">  
           </form>
       </div>
    </div>
    <br>
</div>

<br>

<div class="container">
<div class="row">
<div class="col-sm-10 col-sm-offset-1">
  {% if not past_recall %}
    <p><strong>You Have No Recalls.</strong> Why not <a href="{% url 'recall:create_recall' %}">create one?</a></p>
  {% endif %}
</div>
</div>
<div  class="table-responsive" class="row">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr class="success">
        <th><span>Name</span></th>
        <th><span>Recall Date</span></th>
        <th><span>Recall Status</span></th>
        <th class="text-center"><span>Actions</span></th>
      </tr>
    </thead>
    <tbody>
    {% for schedule in past_recall|dictsort:"date_of_visit" %}   
    
      <tr>
        <td><a href="{{ schedule.get_absolute_url }}">{{ schedule.patient }}</a></td>
        <td>{{ schedule.date_of_recall }}</td>
        <td>{{ schedule.recall_status }}</td>
        <td class="text-center">
            <a class="btn btn-info btn-xs" href="{% url 'recall:update_recall' schedule.pk %}"><span class="glyphicon glyphicon-edit"></span>Edit</a>
            <a class="btn btn-danger btn-xs" href="{% url 'recall:delete_recall' schedule.pk %}"><span class="glyphicon glyphicon-remove"></span>Del</a>
        </td>
      </tr>

    {% endfor %}
    </tbody>
  </table>

 {% if is_paginated %}
   
    
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  
  {% endif %}
  </div>
  </div>
  </div>
 </div> 
{% endblock %}

recall/templates/recall/patient_update.html
{% extends 'dashboard.html' %}

{% load bootstrap %}

{% block content %}

<div style="background-color: #0D96FF !important" class="container-fluid">
	<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12">
			<h1><b>Update Patient</b></h1>
			</div>
		</div>
	</div>
	<br>
</div><br>

<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3">
	<form method="POST" action="" class="form">
		{{ form|bootstrap }}
		{% csrf_token %}
		<input type="submit" value="Update" class="btn btn-success"> 
	</form>
</div>
</div>
</div><br>

{% endblock %}

recall/templates/recall/schedule_confirm_delete.html
{% extends 'dashboard.html' %}

{% load bootstrap3 %}


{% block title %}Delete Recall | {{ block.super }}{% endblock %}

{% block content %}
<div style="background-color: #0D96FF !important" class="container-fluid">
	<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12">
			<h1><b>Delete Recall</b></h1>
			</div>
		</div>
	</div>
	<br>
</div>

<div class="container">
	<div class="row">
		<div class="col-sm-6 col-md-6">
			<form method="POST" action="">
			{% csrf_token %}
			<h3>Are you sure you want to delete a recall for "{{ schedule }}"?</h3>
			{% buttons %}
		    	<button type="submit" class="btn btn-danger">
		      		{% bootstrap_icon "remove" %} Delete
		    	</button>
		  	{% endbuttons %}
			</form>
		</div>
	</div>
</div>
{% endblock %}

recall/templates/recall/schedule_form.html
{% extends 'dashboard.html' %}

{% load bootstrap3 %}

{% load bootstrap %}


{% block title %}Update Recall | {{ block.super }}{% endblock %}

{% block content %}
<div style="background-color: #0D96FF !important" class="container-fluid">
	<br>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12">
			<h1><b>Edit Recall</b></h1>
			</div>
		</div>
	</div>
	<br>
</div>
			{% if messages %}
			{% bootstrap_javascript jquery=1 %}
			{% bootstrap_messages %}
			{% endif %}

<div class="container"><br>
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3" class="form-group">
			<form method="POST" action="">
			{{ form|bootstrap }}
			{% csrf_token %}
			{% buttons %}
		    	<button type="submit" class="btn btn-success">
		      		{% bootstrap_icon "edit" %} Edit
		    	</button>
		  	{% endbuttons %}
			</form>
		</div>
	</div>
</div>
{% endblock %}

recall/templates/recall/view_recall.html
{% extends 'dashboard.html' %}


{% block title %}View Recalls | {{ block.super }}{% endblock %}

{% block content %}
<div style="background:#0D96FF !important" class="container-fluid">
    <br>
    <div class="container">
        <div class="row">
           <h1><b>View Recalls</b></h1>
           <form method="GET" action="">
             <input type="text" class="form-control input-md" name="q" placeholder="Enter Name or Date of Recall(YYYY-MM-DD)" value="{{ request.GET.q }}"/>
             <input type="submit" value="Search" class="btn btn-success">  
           </form>
       </div>
    </div>
    <br>
</div>

<br>

<div class="container">
<div class="row">
<div class="col-sm-10 col-sm-offset-1">
  {% if not view_recall %}
    <p><strong>You Have No Recalls.</strong> Why not <a href="{% url 'recall:create_recall' %}">create one?</a></p>
  {% endif %}
</div>
</div>
<div  class="table-responsive" class="row">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr class="success">
        <th><span>Name</span></th>
        <th><span>Recall Date</span></th>
        <th><span>Recall Status</span></th>
        <th class="text-center"><span>Actions</span></th>
      </tr>
    </thead>
    <tbody>
    {% for schedule in view_recall|dictsort:"date_of_recall" %}  
      <tr>
        <td><a href="{{ schedule.get_absolute_url }}">{{ schedule.patient }}</a></td>
        <td>{{ schedule.date_of_recall }}</td>
        <td>{{ schedule.recall_status }}</td>
        <td class="text-center">
            <a class="btn btn-info btn-xs" href="{% url 'recall:update_recall' schedule.pk %}"><span class="glyphicon glyphicon-edit"></span>Edit</a>
            <a class="btn btn-danger btn-xs" href="{% url 'recall:delete_recall' schedule.pk %}"><span class="glyphicon glyphicon-remove"></span>Del</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

 {% if is_paginated %}
 
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>

  {% endif %}
  </div>
  </div>
  </div>
 </div> 
{% endblock %}