recall/urls.py
from django.conf.urls import url
from recall import views
from .views import CreateScheduleView, ViewScheduleView, PastRecallView, ScheduleDetailView, ScheduleUpdateView, ScheduleDeleteView, ContactView
from .views import PatientFormView, PatientListView, PatientDetailView, PatientUpdateView, PatientDeleteView


app_name = 'recall'
urlpatterns = [
	url(r'^contact/$', ContactView.as_view(), name='contact'),
	url(r'^patient_delete(?P<pk>\d+)$', PatientDeleteView.as_view(), name='patient_delete'),
	url(r'^patient_update(?P<pk>\d+)$', PatientUpdateView.as_view(), name='patient_update'),
	url(r'^patient_detail(?P<pk>\d+)$', PatientDetailView.as_view(), name='patient_detail'),
	url(r'^patient_list/$', PatientListView.as_view(), name='patient_list'),
	url(r'^add_patient/$', PatientFormView.as_view(), name='add_patient'),
	url(r'^detail_recall(?P<pk>\d+)$', ScheduleDetailView.as_view(), name='detail_recall'),
	url(r'^update_recall(?P<pk>\d+)$', ScheduleUpdateView.as_view(), name='update_recall'),
	url(r'^delete_recall(?P<pk>\d+)$', ScheduleDeleteView.as_view(), name='delete_recall'),
	url(r'^past_recall/$', PastRecallView.as_view(), name='past_recall'),
	url(r'^view_recall/$', ViewScheduleView.as_view(), name='view_recall'),
	url(r'^create_recall/$', CreateScheduleView.as_view(), name='create_recall'),
]

recallmanager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView

from recall import urls as recall_url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recall/', include(recall_url)),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

templates/contact.html
{% extends 'layout.html' %}

{% load bootstrap3 %}




{% block title %}Contact | {{ block.super }}{% endblock %}
{% load bootstrap3 %}

{% block content %}
<div style="background-color: #48E4FF !important;" class="jumbotron">
	<div class="container">
		<div class="row">
			<div>
				<h1>Contact Us</h1>

				<form class="form-inline" role="form" action="{% url 'recall:contact' %}" method="post">
					{% csrf_token %}
					{% for field in form %}
					<div class="form-group">
				    {% bootstrap_field field show_label=True placeholder=False %}
					</div>
					{% endfor %}
					<input type="submit" class="btn btn-success" value="Submit" />
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width,initial-scale=1" name=viewport>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Dashboard{% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Add additional CSS in static file -->
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/recall.css' %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
   <nav style="background:#01092B !important" class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-slide-dropdown">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Patient Recall Manager</a>
        </div>
         <div class="collapse navbar-collapse" id="bs-slide-dropdown">
              <ul class="nav navbar-nav navbar-right">
                <li role="presentation" class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Patient<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                       <li><a href="{% url 'recall:add_patient' %}">Add patient</a></li>
                       <li><a href="{% url 'recall:patient_list' %}">View patient</a></li> 
                    </ul>
                </li>
                 <li role="presentation" class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Recall<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                       <li><a href="{% url 'recall:create_recall' %}">Create recall</a></li>
                       <li><a href="{% url 'recall:view_recall' %}">View upcoming recall</a></li>
                       <li><a href="{% url 'recall:past_recall' %}">View past recall</a></li>  
                    </ul>
                </li>
              </ul>
        </div>
        </div>
    </nav>

    <hr>

    {% block content %}{% endblock %}

    <hr>

    <div class="container">
       <footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>
    </div> <!-- /container -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
   
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'layout.html' %}

{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
	<div class="container-fluid">
        <div class="row">
            <div style="background-color: #48E4FF !important;" class="jumbotron">
                <h1>Built For Hospitals And Clinics</h1>
                {% load staticfiles %}
                <img src="{% static 'img/jumbotron.png' %}" style="width: 100%;" />
                <p>Patient Recall Manager is an innovative and intuitive application designed to effectively manage hospital/clinic patient recall process.</p>
                <p><a href="{% url 'recall:create_recall' %}" class="btn btn-danger btn-lg">CONTACT US</a></p>
            </div>
        </div>
    </div> 
    <div class="container">
    	<div class="row">
        	<div style="text-align: center;" class="col-md-12">
        		<h1 class="text-primary">It's time to rethink patient recall management</h1>
        		<p class="lead">Effective patient recall makes absolute clinical and business sense. Whether your goal is to improve clinical care or boast practice revenue, effective patient recall management is at the heart of it all.</p>
        	</div>		
        </div>
    </div><br>

    <div class="jumbotron">
     	<div class="container">
     		<h2>Create recalls easily</h2><br>
	    	<div class="row">
	    		<div style="text-align: left;" class="col-sm-6">
	    		<p>creating recalls is not the same as simply creating an appointment. Following a visit, an <i class="text-primary">On Schedule</i> recall is created with associated information such as the summary of the patient visit, and the reason for the patient recall. This is part of what makes recall more than just an appointment booking process.</p>
	    		<p>After sending a recall reminder on the recall date, <i class="text-primary">A Reminder</i> recall is created for a subsequent future date. This reminder recall can be updated untill the patients next visit where a new on schedule recall will be created.</p>
	    		</div>
	        	<div class="col-sm-6">
	        	{% load staticfiles %}
	        	<img src="{% static 'img/jumbotron2.png' %}" style="width: 50%;" />	
	        	</div>
	    	</div>
	    </div>
    </div>
    <div style="background-color: #fff;" class="jumbotron">
    	<div class="container">
    		<h2>View daily recalls</h2><br>
       		<div class="row">
        		<div class="col-sm-6">
        		{% load staticfiles %}
     			<img src="{% static 'img/jumbotron3.png' %}" style="width: 50%;" />
        		</div>
        		<div style="text-align: left;" class="col-sm-6">
        		<p>With our patient recall manager, its goodbye to manually trying to sort through your recall list on a daily basis.</p>
        		<p>On creation, a recall is automatically added to your recall list and sorted according to the date of recall.</p>	
        		<p>This way, you always find the recalls for the day on top of the list. this saves you the time and energy spent manually trying to sort through your list.</p>
        		<p>Manaully sorting through your recalls is primarily responsible for the ineffectiveness in many recall systems.</p>
        		</div>
        	</div>
       </div>
    </div>
    <div class="jumbotron">
    	<div class="container">
    		<h2>Patient recall/management history at your fingertips</h2><br>
       		<div class="row">
        		<div style="text-align: left;" class="col-sm-6">
        		<p>Our patient recall manager allows you to search and view the recall history for every patient.</p>
        		<p>This allows you have information about the patient management timeline. By clicking on the patients ID, you can access the recall detail page, where more information such as the summary of the patient's visit, date of previous visit, reason for recall and the patient phone number. This functionality allows our recall manager suffice as a <i class="text-primary">simplified EHR system.</i></p>
        		</div>
        		<div class="col-sm-6">
        		{% load static %}
        		<img src="{% static 'img/jumbotron4.png' %}" style="width: 50%;" />	
        		</div>
        	</div>
    	</div>
    </div>
    <div class="container">
    	<div class="row">
        	<div style="text-align: center;" class="col-md-12">
        		<h2 class="text-primary">Patient recall manager is a web application</h2>
        		<p class="lead">This means you can access your recall manager from any device and from any location, even from the comfort of your home!</p>
        	</div>		
        </div>
    </div><br>
    <div style="background-color:  #48E4FF;" class="container-fluid">
    	<div class="row">
        	<div style="text-align: center;" class="col-sm-12">
        		<h2>Let us customise our recall manager for your practice</h2>
        		<p class="lead">we have an incredible team to provide the support you need</p>
        	</div>		
        </div>
    </div><br>


{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width,initial-scale=1" name=viewport>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Recall Manager</title>

    <!-- Latest compiled and minified CSS --> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body style="font-family: 'Slabo 27px', serif;">
    
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'home' %}" class="navbar-brand"><b>Patient <i style="color: red;">Recall</i> Manager</b></a>
          </div>
          <!--<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav navbar-right">
            <li><a style="color: #fff !important" href="{% url 'recall:contact' %}" class="btn btn-danger btn-lg">Contact Us</a></li>
          </ul>
        </div>-->
      </div>
    </div>
    <br>
    {% block content %}


    {% endblock %}
   
    <div class="container">
        <footer>
          <p>&copy; 2017 Practice Companion Nigeria.</p>
          <p>10 Mayne Avenue Calabar.</p>
          <p>08084866827, practicecompanionng@gmail.com</p>
        </footer>
    </div> <!-- /container -->
   

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
   
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>